#!/usr/bin/env bash
#
# GabutPoC deploy — bring up SRS (WebRTC), the control relay, and the web
# dashboard as Docker containers. The server IP is taken as input (argument or
# prompt) and applied to CANDIDATE (SRS ICE) and web-viewer/config.js (dashboard).
#
# Usage:
#   ./deploy.sh                    # prompts for the server IP (deploy + build APK)
#   ./deploy.sh 192.168.100.22     # non-interactive
#   ./deploy.sh install [serial]   # install the APK to a connected kiosk (via adb)
#   ./deploy.sh down               # stop & remove the containers
#
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
COMPOSE_DIR="$HERE/docker"
CONFIG_JS="$HERE/web-viewer/config.js"

# --- pick the docker compose command (v2 plugin or legacy) ---
if docker compose version >/dev/null 2>&1; then DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then DC="docker-compose"
else echo "ERROR: docker compose tidak ditemukan. Install Docker dulu."; exit 1
fi

# --- teardown ---
if [ "${1:-}" = "down" ] || [ "${1:-}" = "stop" ]; then
  ( cd "$COMPOSE_DIR" && $DC down )
  echo "Dihentikan."
  exit 0
fi

# --- locate adb ---
find_adb() {
  if command -v adb >/dev/null 2>&1; then command -v adb; return; fi
  for c in "${ANDROID_HOME:-}" "${ANDROID_SDK_ROOT:-}" "$HOME/Library/Android/sdk" "$HOME/Android/Sdk" "/opt/homebrew/share/android-commandlinetools"; do
    [ -n "$c" ] && [ -x "$c/platform-tools/adb" ] && { echo "$c/platform-tools/adb"; return; }
  done
}

# --- install APK to a kiosk you control, via adb ---
#
# Play Protect blocks this APK because screen-capture + accessibility remote
# control matches its spyware heuristic. On a device YOU OWN and reach over adb,
# disabling the adb-install verifier is a legitimate sideload path. It does NOT
# disguise the app — for general distribution use managed Google Play / MDM.
if [ "${1:-}" = "install" ]; then
  ADB="$(find_adb)"
  [ -n "$ADB" ] || { echo "ERROR: adb tidak ditemukan. Set ANDROID_HOME / pasang platform-tools."; exit 1; }
  APK="$HERE/android/app/build/outputs/apk/debug/GabutPoC-universal-debug.apk"
  [ -f "$APK" ] || { echo "ERROR: APK belum ada — jalankan './deploy.sh <ip>' dulu."; exit 1; }
  SERIAL="${2:-}"
  echo "==> Perangkat terhubung:"; "$ADB" devices
  run_adb() { if [ -n "$SERIAL" ]; then "$ADB" -s "$SERIAL" "$@"; else "$ADB" "$@"; fi; }
  echo "==> Menonaktifkan pemindai install-adb (perangkat milikmu)…"
  run_adb shell settings put global verifier_verify_adb_installs 0 || true
  run_adb shell settings put global package_verifier_enable 0 || true
  echo "==> Install $APK"
  run_adb install -r -g "$APK"
  echo ""
  echo "Selesai. Buka GabutPoC di kiosk → Aktifkan Stream + Aktifkan Full Control."
  echo "Jika masih diblok: di perangkat, Play Store → Play Protect → ⚙️ → matikan 'Scan apps'."
  exit 0
fi

# --- get server IP ---
IP="${1:-}"
if [ -z "$IP" ]; then
  printf "Masukkan IP server (LAN, mis. 192.168.100.22): "
  read -r IP
fi

# basic IPv4 validation
if ! printf '%s' "$IP" | grep -Eq '^([0-9]{1,3}\.){3}[0-9]{1,3}$'; then
  echo "ERROR: '$IP' bukan alamat IPv4 yang valid."; exit 1
fi

echo "==> Server IP: $IP"

# --- single source of truth: SRS_HOST (APK + dashboard) ---
GRADLE_PROPS="$HERE/android/gradle.properties"
if [ -f "$GRADLE_PROPS" ] && grep -q '^SRS_HOST=' "$GRADLE_PROPS"; then
  sed -i.bak "s|^SRS_HOST=.*|SRS_HOST=$IP:1985|" "$GRADLE_PROPS" && rm -f "$GRADLE_PROPS.bak"
  echo "==> android/gradle.properties SRS_HOST -> $IP:1985"
fi
cat > "$CONFIG_JS" <<EOF
// AUTO-GENERATED by deploy.sh — server address for the web dashboard.
window.SRS_HOST = '$IP:1985';
EOF
echo "==> web-viewer/config.js -> $IP:1985"

# --- deploy containers ---
echo "==> Menjalankan container (build bila perlu)…"
( cd "$COMPOSE_DIR" && CANDIDATE="$IP" $DC up -d --build )

# --- build the Android APK with this IP baked in ---
build_apk() {
  if [ "${SKIP_APK:-}" = "1" ]; then echo "==> SKIP_APK=1 — lewati build APK."; return 0; fi
  local AND="$HERE/android"
  [ -x "$AND/gradlew" ] || { echo "!! $AND/gradlew tidak ada — lewati build APK."; return 0; }

  # JDK 17
  if [ -z "${JAVA_HOME:-}" ] && [ -x /usr/libexec/java_home ]; then
    JAVA_HOME="$(/usr/libexec/java_home -v 17 2>/dev/null || true)"; export JAVA_HOME
  fi
  [ -n "${JAVA_HOME:-}" ] || { echo "!! JAVA_HOME (JDK 17) tak ditemukan — lewati build APK. Set JAVA_HOME lalu jalankan lagi."; return 0; }

  # Android SDK
  local SDK="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-}}"
  if [ -z "$SDK" ] && [ -f "$AND/local.properties" ]; then SDK="$(grep '^sdk.dir=' "$AND/local.properties" | cut -d= -f2-)"; fi
  if [ -z "$SDK" ]; then
    for c in "$HOME/Library/Android/sdk" "$HOME/Android/Sdk" "/opt/homebrew/share/android-commandlinetools" "/usr/lib/android-sdk"; do
      [ -d "$c/platforms" ] && SDK="$c" && break
    done
  fi
  [ -n "$SDK" ] && [ -d "$SDK" ] || { echo "!! Android SDK tak ditemukan — lewati build APK. Set ANDROID_HOME lalu jalankan lagi."; return 0; }
  echo "sdk.dir=$SDK" > "$AND/local.properties"

  echo "==> Build APK (SRS_HOST=$IP:1985)…"
  ( cd "$AND" && JAVA_HOME="$JAVA_HOME" ANDROID_HOME="$SDK" ./gradlew --no-daemon assembleDebug -q )
  APK_OUT="$AND/app/build/outputs/apk/debug/GabutPoC-universal-debug.apk"
  [ -f "$APK_OUT" ] && echo "==> APK: $APK_OUT ($(du -h "$APK_OUT" | cut -f1))"
}
build_apk

echo ""
echo "==> Status:"
( cd "$COMPOSE_DIR" && $DC ps )

cat <<EOF

Selesai. Endpoint:
  Dashboard   : http://$IP:8088/dashboard.html   (menu Stream & Remote)
  SRS API     : http://$IP:1985/api/v1/streams/
  WHIP (kiosk): http://$IP:1985/rtc/v1/whip/?app=live&stream=<device-id>
  WHEP (play) : http://$IP:1985/rtc/v1/whep/?app=live&stream=<device-id>
  Relay (ctrl): ws://$IP:8092
  APK kiosk   : ${APK_OUT:-(dilewati — lihat pesan di atas)}

Pasang ke kiosk (via adb, lewati blokir Play Protect):  ./deploy.sh install [serial]
Lalu di kiosk: Aktifkan Stream + Aktifkan Full Control.
Hentikan semua: ./deploy.sh down   ·   Lewati build APK: SKIP_APK=1 ./deploy.sh $IP

Port yang dibuka:
  1935/tcp RTMP · 1985/tcp API+WHIP/WHEP · 8000/udp media WebRTC
  8080/tcp SRS http · 8088/tcp dashboard · 8092/tcp relay ws
EOF
